/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    boats: Boat;
    people: Person;
    courses: Course;
    'training-events': TrainingEvent;
    'cruise-events': CruiseEvent;
    media: Media;
    users: User;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    boats: BoatsSelect<false> | BoatsSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    'training-events': TrainingEventsSelect<false> | TrainingEventsSelect<true>;
    'cruise-events': CruiseEventsSelect<false> | CruiseEventsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    'component-labels': ComponentLabel;
    'fleet-location': FleetLocation;
    'cruise-map': CruiseMap;
    'page-not-found': PageNotFound;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'component-labels': ComponentLabelsSelect<false> | ComponentLabelsSelect<true>;
    'fleet-location': FleetLocationSelect<false> | FleetLocationSelect<true>;
    'cruise-map': CruiseMapSelect<false> | CruiseMapSelect<true>;
    'page-not-found': PageNotFoundSelect<false> | PageNotFoundSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL slug. Use "home" for the homepage (route "/").
   */
  slug: string;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  /**
   * Compose the page by adding, reordering and editing sections.
   */
  layout?:
    | (
        | HeroHomeBlock
        | HeroBasicBlock
        | SectionImageSideBlock
        | SectionBackgroundImageBlock
        | SectionHeadingBlock
        | SimpleContentBlock
        | CardGridBlock
        | RichTextCardsBlock
        | PeopleSectionBlock
        | ParagraphsSectionBlock
        | UpcomingCoursesBlock
        | CoursesTabsBlock
        | CruiseCarouselBlock
        | FleetLocationBlock
        | FleetListBlock
        | GalleryBlock
        | JoinTabsBlock
        | MembershipFormBlock
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroHomeBlock".
 */
export interface HeroHomeBlock {
  kicker?: string | null;
  /**
   * Use line breaks for multi-line headings.
   */
  heading: string;
  coordinates?: string | null;
  /**
   * Path to an asset in /public (e.g. /figmaAssets/home/cruises.png).
   */
  backgroundImage?: string | null;
  backgroundAlt?: string | null;
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  actions?:
    | {
        label: string;
        href: string;
        external?: boolean | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'heroHome';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBasicBlock".
 */
export interface HeroBasicBlock {
  kicker?: string | null;
  heading: string;
  body?: string | null;
  /**
   * Path to an asset in /public (e.g. /figmaAssets/home/cruises.png).
   */
  imageSrc?: string | null;
  imageAlt?: string | null;
  cta?: {
    label?: string | null;
    href?: string | null;
    /**
     * Open in a new tab / treat as an external link.
     */
    external?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'heroBasic';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionImageSideBlock".
 */
export interface SectionImageSideBlock {
  kicker?: string | null;
  heading: string;
  body?: string | null;
  cta?: {
    label?: string | null;
    href?: string | null;
    /**
     * Open in a new tab / treat as an external link.
     */
    external?: boolean | null;
  };
  /**
   * Path to an asset in /public (e.g. /figmaAssets/home/cruises.png).
   */
  image?: string | null;
  imageAlt?: string | null;
  align?: ('right' | 'left') | null;
  variant?: ('secondary' | 'tertiary') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'sectionImageSide';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionBackgroundImageBlock".
 */
export interface SectionBackgroundImageBlock {
  kicker?: string | null;
  heading: string;
  body?: string | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  /**
   * Path to an asset in /public (e.g. /figmaAssets/home/cruises.png).
   */
  imageSrc?: string | null;
  imageAlt?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'sectionBackgroundImage';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionHeadingBlock".
 */
export interface SectionHeadingBlock {
  kicker?: string | null;
  heading: string;
  body?: string | null;
  as?: ('h1' | 'h2' | 'h3') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'sectionHeading';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SimpleContentBlock".
 */
export interface SimpleContentBlock {
  label?: string | null;
  heading: string;
  body?: string | null;
  actions?:
    | {
        label: string;
        href: string;
        external?: boolean | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'simpleContent';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGridBlock".
 */
export interface CardGridBlock {
  sectionKicker?: string | null;
  sectionHeading?: string | null;
  cards?:
    | {
        kicker?: string | null;
        heading: string;
        body?: string | null;
        cta?: {
          label?: string | null;
          href?: string | null;
          /**
           * Open in a new tab / treat as an external link.
           */
          external?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cardGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextCardsBlock".
 */
export interface RichTextCardsBlock {
  cards?:
    | {
        kicker?: string | null;
        heading: string;
        blocks?:
          | (
              | {
                  text: string;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'paragraph';
                }
              | {
                  variant?: ('spaced' | 'compact') | null;
                  items?:
                    | {
                        item: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'list';
                }
              | {
                  variant?: ('spaced' | 'compact') | null;
                  items?:
                    | {
                        item: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'orderedList';
                }
              | {
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'break';
                }
            )[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richTextCards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PeopleSectionBlock".
 */
export interface PeopleSectionBlock {
  kicker?: string | null;
  heading: string;
  body?: string | null;
  group: 'board' | 'instructors' | 'skippers';
  id?: string | null;
  blockName?: string | null;
  blockType: 'peopleSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ParagraphsSectionBlock".
 */
export interface ParagraphsSectionBlock {
  kicker?: string | null;
  heading: string;
  paragraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    href?: string | null;
    /**
     * Open in a new tab / treat as an external link.
     */
    external?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'paragraphsSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "UpcomingCoursesBlock".
 */
export interface UpcomingCoursesBlock {
  kicker?: string | null;
  heading: string;
  body?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'upcomingCourses';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CoursesTabsBlock".
 */
export interface CoursesTabsBlock {
  ariaLabel?: string | null;
  emptyMessage?: string | null;
  rateNote?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'coursesTabs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CruiseCarouselBlock".
 */
export interface CruiseCarouselBlock {
  kicker?: string | null;
  heading: string;
  body?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cruiseCarousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FleetLocationBlock".
 */
export interface FleetLocationBlock {
  /**
   * Remove outer padding (used on the cruises page).
   */
  flush?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'fleetLocation';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FleetListBlock".
 */
export interface FleetListBlock {
  heading?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'fleetList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  kicker?: string | null;
  heading: string;
  body?: string | null;
  src?: string | null;
  overlaySrc?: string | null;
  alt?: string | null;
  totalSlides?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "JoinTabsBlock".
 */
export interface JoinTabsBlock {
  ariaLabel?: string | null;
  tabs?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Structured content for the four join tabs (membership, fees, testerDay, gear).
   */
  panels:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'joinTabs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MembershipFormBlock".
 */
export interface MembershipFormBlock {
  /**
   * Labels and copy for the membership application form (matches MembershipApplicationContent.form).
   */
  form:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'membershipForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "boats".
 */
export interface Boat {
  id: number;
  name: string;
  model?: string | null;
  year?: string | null;
  description?: string | null;
  /**
   * Path to an asset in /public (e.g. /figmaAssets/home/cruises.png).
   */
  photo?: string | null;
  photoAlt?: string | null;
  specsLeft?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  specsRight?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Sort order (ascending).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  name: string;
  title?: string | null;
  dept?: string | null;
  email?: string | null;
  /**
   * Path to an asset in /public (e.g. /figmaAssets/home/cruises.png).
   */
  photo?: string | null;
  photoAlt?: string | null;
  group: 'board' | 'instructors' | 'skippers';
  /**
   * Sort order (ascending).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  /**
   * Which level tab this course appears under.
   */
  tab: 'Beginner' | 'Intermediate' | 'Advanced' | 'All Levels';
  level?: ('Beginner' | 'Intermediate' | 'Advanced' | 'All Levels') | null;
  desc?: string | null;
  items?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  prices?:
    | {
        from?: string | null;
        til?: string | null;
        amount?: string | null;
        duration?: string | null;
        id?: string | null;
      }[]
    | null;
  notes?: string | null;
  /**
   * Sort order (ascending).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-events".
 */
export interface TrainingEvent {
  id: number;
  title: string;
  dates?: string | null;
  yacht?: string | null;
  model?: string | null;
  skipper?: string | null;
  /**
   * Sort order (ascending).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cruise-events".
 */
export interface CruiseEvent {
  id: number;
  title: string;
  dates?: string | null;
  yacht?: string | null;
  model?: string | null;
  skipper?: string | null;
  /**
   * Path to an asset in /public (e.g. /figmaAssets/home/cruises.png).
   */
  imageSrc?: string | null;
  imageAlt?: string | null;
  /**
   * Sort order (ascending).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'boats';
        value: number | Boat;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'training-events';
        value: number | TrainingEvent;
      } | null)
    | ({
        relationTo: 'cruise-events';
        value: number | CruiseEvent;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  layout?:
    | T
    | {
        heroHome?: T | HeroHomeBlockSelect<T>;
        heroBasic?: T | HeroBasicBlockSelect<T>;
        sectionImageSide?: T | SectionImageSideBlockSelect<T>;
        sectionBackgroundImage?: T | SectionBackgroundImageBlockSelect<T>;
        sectionHeading?: T | SectionHeadingBlockSelect<T>;
        simpleContent?: T | SimpleContentBlockSelect<T>;
        cardGrid?: T | CardGridBlockSelect<T>;
        richTextCards?: T | RichTextCardsBlockSelect<T>;
        peopleSection?: T | PeopleSectionBlockSelect<T>;
        paragraphsSection?: T | ParagraphsSectionBlockSelect<T>;
        upcomingCourses?: T | UpcomingCoursesBlockSelect<T>;
        coursesTabs?: T | CoursesTabsBlockSelect<T>;
        cruiseCarousel?: T | CruiseCarouselBlockSelect<T>;
        fleetLocation?: T | FleetLocationBlockSelect<T>;
        fleetList?: T | FleetListBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        joinTabs?: T | JoinTabsBlockSelect<T>;
        membershipForm?: T | MembershipFormBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroHomeBlock_select".
 */
export interface HeroHomeBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  coordinates?: T;
  backgroundImage?: T;
  backgroundAlt?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  actions?:
    | T
    | {
        label?: T;
        href?: T;
        external?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBasicBlock_select".
 */
export interface HeroBasicBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  body?: T;
  imageSrc?: T;
  imageAlt?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
        external?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionImageSideBlock_select".
 */
export interface SectionImageSideBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  body?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
        external?: T;
      };
  image?: T;
  imageAlt?: T;
  align?: T;
  variant?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionBackgroundImageBlock_select".
 */
export interface SectionBackgroundImageBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  body?: T;
  ctaLabel?: T;
  ctaHref?: T;
  imageSrc?: T;
  imageAlt?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionHeadingBlock_select".
 */
export interface SectionHeadingBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  body?: T;
  as?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SimpleContentBlock_select".
 */
export interface SimpleContentBlockSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  body?: T;
  actions?:
    | T
    | {
        label?: T;
        href?: T;
        external?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGridBlock_select".
 */
export interface CardGridBlockSelect<T extends boolean = true> {
  sectionKicker?: T;
  sectionHeading?: T;
  cards?:
    | T
    | {
        kicker?: T;
        heading?: T;
        body?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
              external?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextCardsBlock_select".
 */
export interface RichTextCardsBlockSelect<T extends boolean = true> {
  cards?:
    | T
    | {
        kicker?: T;
        heading?: T;
        blocks?:
          | T
          | {
              paragraph?:
                | T
                | {
                    text?: T;
                    id?: T;
                    blockName?: T;
                  };
              list?:
                | T
                | {
                    variant?: T;
                    items?:
                      | T
                      | {
                          item?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              orderedList?:
                | T
                | {
                    variant?: T;
                    items?:
                      | T
                      | {
                          item?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              break?:
                | T
                | {
                    id?: T;
                    blockName?: T;
                  };
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PeopleSectionBlock_select".
 */
export interface PeopleSectionBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  body?: T;
  group?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ParagraphsSectionBlock_select".
 */
export interface ParagraphsSectionBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  paragraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
        external?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "UpcomingCoursesBlock_select".
 */
export interface UpcomingCoursesBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  body?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CoursesTabsBlock_select".
 */
export interface CoursesTabsBlockSelect<T extends boolean = true> {
  ariaLabel?: T;
  emptyMessage?: T;
  rateNote?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CruiseCarouselBlock_select".
 */
export interface CruiseCarouselBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  body?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FleetLocationBlock_select".
 */
export interface FleetLocationBlockSelect<T extends boolean = true> {
  flush?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FleetListBlock_select".
 */
export interface FleetListBlockSelect<T extends boolean = true> {
  heading?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  body?: T;
  src?: T;
  overlaySrc?: T;
  alt?: T;
  totalSlides?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "JoinTabsBlock_select".
 */
export interface JoinTabsBlockSelect<T extends boolean = true> {
  ariaLabel?: T;
  tabs?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  panels?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MembershipFormBlock_select".
 */
export interface MembershipFormBlockSelect<T extends boolean = true> {
  form?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "boats_select".
 */
export interface BoatsSelect<T extends boolean = true> {
  name?: T;
  model?: T;
  year?: T;
  description?: T;
  photo?: T;
  photoAlt?: T;
  specsLeft?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  specsRight?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  dept?: T;
  email?: T;
  photo?: T;
  photoAlt?: T;
  group?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  tab?: T;
  level?: T;
  desc?: T;
  items?:
    | T
    | {
        item?: T;
        id?: T;
      };
  prices?:
    | T
    | {
        from?: T;
        til?: T;
        amount?: T;
        duration?: T;
        id?: T;
      };
  notes?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-events_select".
 */
export interface TrainingEventsSelect<T extends boolean = true> {
  title?: T;
  dates?: T;
  yacht?: T;
  model?: T;
  skipper?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cruise-events_select".
 */
export interface CruiseEventsSelect<T extends boolean = true> {
  title?: T;
  dates?: T;
  yacht?: T;
  model?: T;
  skipper?: T;
  imageSrc?: T;
  imageAlt?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  metadata?: {
    title?: string | null;
    description?: string | null;
  };
  coordinates?: string | null;
  location?: string | null;
  contactHeading?: string | null;
  email?: string | null;
  facebookLabel?: string | null;
  facebookUrl?: string | null;
  logoAlt?: string | null;
  copyright?: string | null;
  registration?: string | null;
  headerJoinLabel?: string | null;
  membersLabel?: string | null;
  primaryNavLabel?: string | null;
  mobileNavLabel?: string | null;
  openNavLabel?: string | null;
  closeNavLabel?: string | null;
  logoHref?: string | null;
  logoSrc?: string | null;
  footerBackgroundSrc?: string | null;
  footerCompassSrc?: string | null;
  footerLogoSrc?: string | null;
  siteFooterBackgroundSrc?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  primaryNavItems?:
    | {
        label: string;
        href: string;
        divider?: boolean | null;
        id?: string | null;
      }[]
    | null;
  footerNavLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "component-labels".
 */
export interface ComponentLabel {
  id: number;
  cardBoat?: {
    kicker?: string | null;
    built?: string | null;
    specifications?: string | null;
  };
  cardCourse?: {
    from?: string | null;
    till?: string | null;
    notes?: string | null;
  };
  cardEvent?: {
    skipper?: string | null;
  };
  cruiseCarousel?: {
    previous?: string | null;
    next?: string | null;
    arrowSrc?: string | null;
  };
  gallery?: {
    previous?: string | null;
    next?: string | null;
    previousIcon?: string | null;
    nextIcon?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fleet-location".
 */
export interface FleetLocation {
  id: number;
  heading?: string | null;
  body?: string | null;
  mapAriaLabel?: string | null;
  mapSrc?: string | null;
  logoSrc?: string | null;
  concordeMarkerSrc?: string | null;
  speedbirdMarkerSrc?: string | null;
  concordeLabel?: string | null;
  speedbirdLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cruise-map".
 */
export interface CruiseMap {
  id: number;
  mapSrc?: string | null;
  mapAlt?: string | null;
  logoSrc?: string | null;
  speedbirdMarkerSrc?: string | null;
  speedbirdMarkerAlt?: string | null;
  concordeMarkerSrc?: string | null;
  concordeMarkerAlt?: string | null;
  concordeLabel?: string | null;
  speedbirdLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-not-found".
 */
export interface PageNotFound {
  id: number;
  label?: string | null;
  heading?: string | null;
  body?: string | null;
  action?: {
    label?: string | null;
    href?: string | null;
    /**
     * Open in a new tab / treat as an external link.
     */
    external?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  metadata?:
    | T
    | {
        title?: T;
        description?: T;
      };
  coordinates?: T;
  location?: T;
  contactHeading?: T;
  email?: T;
  facebookLabel?: T;
  facebookUrl?: T;
  logoAlt?: T;
  copyright?: T;
  registration?: T;
  headerJoinLabel?: T;
  membersLabel?: T;
  primaryNavLabel?: T;
  mobileNavLabel?: T;
  openNavLabel?: T;
  closeNavLabel?: T;
  logoHref?: T;
  logoSrc?: T;
  footerBackgroundSrc?: T;
  footerCompassSrc?: T;
  footerLogoSrc?: T;
  siteFooterBackgroundSrc?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  primaryNavItems?:
    | T
    | {
        label?: T;
        href?: T;
        divider?: T;
        id?: T;
      };
  footerNavLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "component-labels_select".
 */
export interface ComponentLabelsSelect<T extends boolean = true> {
  cardBoat?:
    | T
    | {
        kicker?: T;
        built?: T;
        specifications?: T;
      };
  cardCourse?:
    | T
    | {
        from?: T;
        till?: T;
        notes?: T;
      };
  cardEvent?:
    | T
    | {
        skipper?: T;
      };
  cruiseCarousel?:
    | T
    | {
        previous?: T;
        next?: T;
        arrowSrc?: T;
      };
  gallery?:
    | T
    | {
        previous?: T;
        next?: T;
        previousIcon?: T;
        nextIcon?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fleet-location_select".
 */
export interface FleetLocationSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  mapAriaLabel?: T;
  mapSrc?: T;
  logoSrc?: T;
  concordeMarkerSrc?: T;
  speedbirdMarkerSrc?: T;
  concordeLabel?: T;
  speedbirdLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cruise-map_select".
 */
export interface CruiseMapSelect<T extends boolean = true> {
  mapSrc?: T;
  mapAlt?: T;
  logoSrc?: T;
  speedbirdMarkerSrc?: T;
  speedbirdMarkerAlt?: T;
  concordeMarkerSrc?: T;
  concordeMarkerAlt?: T;
  concordeLabel?: T;
  speedbirdLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-not-found_select".
 */
export interface PageNotFoundSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  body?: T;
  action?:
    | T
    | {
        label?: T;
        href?: T;
        external?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}