/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    boats: Boat;
    'cruise-events': CruiseEvent;
    courses: Course;
    'training-events': TrainingEvent;
    forms: Form;
    'form-submissions': FormSubmission;
    users: User;
    people: Person;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    boats: BoatsSelect<false> | BoatsSelect<true>;
    'cruise-events': CruiseEventsSelect<false> | CruiseEventsSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    'training-events': TrainingEventsSelect<false> | TrainingEventsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'fleet-location': FleetLocation;
    'cruise-map': CruiseMap;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'fleet-location': FleetLocationSelect<false> | FleetLocationSelect<true>;
    'cruise-map': CruiseMapSelect<false> | CruiseMapSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * e.g. "the-club", "fleet", "join". Use "home" for the homepage (route "/").
   */
  slug: string;
  /**
   * Compose the page by adding, reordering and editing sections.
   */
  pageSections?:
    | (
        | HeroHomeBlock
        | SectionHeaderBlock
        | SectionHeadingBlock
        | SectionImageParalaxBlock
        | SectionImageSideBlock
        | SectionBackgroundImageBlock
        | SectionCenterBlock
        | SectionGalleryBlock
        | SectionFleetLocationBlock
        | SectionFleetBlock
        | SectionPeopleBlock
        | SectionParagraphsBlock
        | SectionEventsBlock
        | SectionCardsBlock
        | SectionTabsBlock
        | SectionContentBlock
        | MembershipApplicationFormBlock
        | FormEmbedBlock
        | NauticalMapBlock
      )[]
    | null;
  /**
   * Add this page to the header and/or footer menus.
   */
  nav?: {
    showIn?: ('header' | 'footer')[] | null;
    /**
     * Defaults to the page title.
     */
    navLabel?: string | null;
    /**
     * Lower numbers appear first.
     */
    navOrder?: number | null;
    /**
     * Show the | separator after this item in the header.
     */
    divider?: boolean | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroHomeBlock".
 */
export interface HeroHomeBlock {
  kicker?: string | null;
  /**
   * Use line breaks for multi-line headings.
   */
  heading: string;
  coordinates?: string | null;
  backgroundImage?: (number | null) | Media;
  /**
   * Accessible description. Falls back to the asset's own alt text.
   */
  backgroundAlt?: string | null;
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  actions?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'heroHome';
}
/**
 * Images, documents, and SVGs used across the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionHeaderBlock".
 */
export interface SectionHeaderBlock {
  kicker?: string | null;
  heading: string;
  body?: string | null;
  image?: (number | null) | Media;
  /**
   * Accessible description. Falls back to the asset's own alt text.
   */
  imageAlt?: string | null;
  cta?: {
    label?: string | null;
    href?: string | null;
    /**
     * Open in a new tab / treat as an external link.
     */
    external?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'sectionHeader';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionHeadingBlock".
 */
export interface SectionHeadingBlock {
  kicker?: string | null;
  heading: string;
  body?: string | null;
  as?: ('h1' | 'h2' | 'h3') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'sectionHeading';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionImageParalaxBlock".
 */
export interface SectionImageParalaxBlock {
  showHeading?: boolean | null;
  sectionHeading?: {
    kicker?: string | null;
    heading: string;
    body?: string | null;
  };
  kicker?: string | null;
  heading: string;
  body?: string | null;
  cta?: {
    label?: string | null;
    href?: string | null;
    /**
     * Open in a new tab / treat as an external link.
     */
    external?: boolean | null;
  };
  image?: (number | null) | Media;
  /**
   * Accessible description. Falls back to the asset's own alt text.
   */
  imageAlt?: string | null;
  align?: ('right' | 'left') | null;
  variant?: ('secondary' | 'tertiary') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'sectionImageParalax';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionImageSideBlock".
 */
export interface SectionImageSideBlock {
  showHeading?: boolean | null;
  sectionHeading?: {
    kicker?: string | null;
    heading: string;
    body?: string | null;
  };
  boat: number | Boat;
  imagePosition?: ('left' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'sectionImageSide';
}
/**
 * Vessel fleet profiles shown on the Fleet page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "boats".
 */
export interface Boat {
  id: number;
  name: string;
  model?: string | null;
  year?: string | null;
  description?: string | null;
  photo?: (number | null) | Media;
  /**
   * Accessible description. Falls back to the asset's own alt text.
   */
  photoAlt?: string | null;
  specsLeft?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  specsRight?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * AIS transponder number — enables live position tracking on map cards.
   */
  mmsi?: string | null;
  /**
   * Auto-populated by the AIS tracker — no need to edit.
   */
  lastPosition?: {
    lat?: number | null;
    lon?: number | null;
    sog?: number | null;
    cog?: number | null;
    reportedAt?: string | null;
  };
  /**
   * Sort order (ascending).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionBackgroundImageBlock".
 */
export interface SectionBackgroundImageBlock {
  kicker?: string | null;
  heading: string;
  body?: string | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  image?: (number | null) | Media;
  /**
   * Accessible description. Falls back to the asset's own alt text.
   */
  imageAlt?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'sectionBackgroundImage';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionCenterBlock".
 */
export interface SectionCenterBlock {
  heading?: string | null;
  body?: string | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'sectionCenter';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionGalleryBlock".
 */
export interface SectionGalleryBlock {
  showHeading?: boolean | null;
  sectionHeading?: {
    kicker?: string | null;
    heading: string;
    body?: string | null;
  };
  image: number | Media;
  /**
   * Accessible description. Falls back to the asset's own alt text.
   */
  alt?: string | null;
  overlayImage?: (number | null) | Media;
  /**
   * Accessible description. Falls back to the asset's own alt text.
   */
  overlayAlt?: string | null;
  totalSlides?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'sectionGallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionFleetLocationBlock".
 */
export interface SectionFleetLocationBlock {
  /**
   * Remove outer padding (edge-to-edge).
   */
  flush?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'sectionFleetLocation';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionFleetBlock".
 */
export interface SectionFleetBlock {
  showHeading?: boolean | null;
  sectionHeading?: {
    kicker?: string | null;
    heading: string;
    body?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'sectionFleet';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionPeopleBlock".
 */
export interface SectionPeopleBlock {
  showHeading?: boolean | null;
  sectionHeading?: {
    kicker?: string | null;
    heading: string;
    body?: string | null;
  };
  group: 'board' | 'instructors' | 'skippers';
  id?: string | null;
  blockName?: string | null;
  blockType: 'sectionPeople';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionParagraphsBlock".
 */
export interface SectionParagraphsBlock {
  kicker?: string | null;
  heading: string;
  paragraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    href?: string | null;
    /**
     * Open in a new tab / treat as an external link.
     */
    external?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'sectionParagraphs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionEventsBlock".
 */
export interface SectionEventsBlock {
  showHeading?: boolean | null;
  sectionHeading?: {
    kicker?: string | null;
    heading: string;
    body?: string | null;
  };
  source: 'training-events' | 'cruise-events';
  display?: ('grid' | 'carousel') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'sectionEvents';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionCardsBlock".
 */
export interface SectionCardsBlock {
  showHeading?: boolean | null;
  sectionHeading?: {
    kicker?: string | null;
    heading: string;
    body?: string | null;
  };
  columns?: ('2' | '3') | null;
  cards?:
    | (
        | CardLrgBlock
        | CardMedBlock
        | CardWideBlock
        | CardEventBlock
        | CardCourseBlock
        | CardBoatBlock
        | CardPersonBlock
        | CardFleetMapBlock
        | FeeItemBlock
        | FeeGroupBlock
        | RichTextContentBlock
      )[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'sectionCards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardLrgBlock".
 */
export interface CardLrgBlock {
  kicker?: string | null;
  heading: string;
  body?:
    | (
        | {
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraph';
          }
        | {
            variant?: ('spaced' | 'compact') | null;
            items?:
              | {
                  item: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'list';
          }
        | {
            variant?: ('spaced' | 'compact') | null;
            items?:
              | {
                  item: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'orderedList';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'break';
          }
      )[]
    | null;
  cta?: {
    label?: string | null;
    href?: string | null;
    /**
     * Open in a new tab / treat as an external link.
     */
    external?: boolean | null;
  };
  variant?: ('tertiary' | 'secondary' | 'primary') | null;
  /**
   * Draw a hairline border around the card.
   */
  bordered?: boolean | null;
  fullWidth?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cardLrg';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardMedBlock".
 */
export interface CardMedBlock {
  heading: string;
  body?:
    | (
        | {
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraph';
          }
        | {
            variant?: ('spaced' | 'compact') | null;
            items?:
              | {
                  item: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'list';
          }
        | {
            variant?: ('spaced' | 'compact') | null;
            items?:
              | {
                  item: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'orderedList';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'break';
          }
      )[]
    | null;
  fullWidth?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cardMed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardWideBlock".
 */
export interface CardWideBlock {
  label?: string | null;
  heading: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cardWide';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardEventBlock".
 */
export interface CardEventBlock {
  title: string;
  dates?: string | null;
  yacht?: string | null;
  model?: string | null;
  skipper?: string | null;
  image?: (number | null) | Media;
  /**
   * Accessible description. Falls back to the asset's own alt text.
   */
  imageAlt?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cardEvent';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardCourseBlock".
 */
export interface CardCourseBlock {
  course: number | Course;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cardCourse';
}
/**
 * Course curriculum (e.g. Competent Crew, Day Skipper).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  /**
   * Which level tab this course appears under.
   */
  tab: 'Beginner' | 'Intermediate' | 'Advanced' | 'All Levels';
  level?: ('Beginner' | 'Intermediate' | 'Advanced' | 'All Levels') | null;
  desc?: string | null;
  items?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  prices?:
    | {
        from?: string | null;
        til?: string | null;
        amount?: string | null;
        duration?: string | null;
        id?: string | null;
      }[]
    | null;
  notes?: string | null;
  /**
   * Sort order (ascending).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardBoatBlock".
 */
export interface CardBoatBlock {
  boat: number | Boat;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cardBoat';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardPersonBlock".
 */
export interface CardPersonBlock {
  person: number | Person;
  layout?: ('club' | 'default') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cardPerson';
}
/**
 * Committee members, staff, and instructors shown on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  name: string;
  title?: string | null;
  dept?: string | null;
  email?: string | null;
  photo?: (number | null) | Media;
  /**
   * Accessible description. Falls back to the asset's own alt text.
   */
  photoAlt?: string | null;
  group: 'board' | 'instructors' | 'skippers';
  /**
   * Sort order (ascending).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardFleetMapBlock".
 */
export interface CardFleetMapBlock {
  id?: string | null;
  blockName?: string | null;
  blockType: 'cardFleetMap';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeeItemBlock".
 */
export interface FeeItemBlock {
  heading: string;
  price?: string | null;
  unit?: string | null;
  description?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'feeItem';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeeGroupBlock".
 */
export interface FeeGroupBlock {
  heading: string;
  body?: string | null;
  note?: string | null;
  fees?: FeeItemBlock[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'feeGroup';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextContentBlock".
 */
export interface RichTextContentBlock {
  body?:
    | (
        | {
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraph';
          }
        | {
            variant?: ('spaced' | 'compact') | null;
            items?:
              | {
                  item: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'list';
          }
        | {
            variant?: ('spaced' | 'compact') | null;
            items?:
              | {
                  item: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'orderedList';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'break';
          }
      )[]
    | null;
  size?: ('default' | 'lead') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionTabsBlock".
 */
export interface SectionTabsBlock {
  ariaLabel?: string | null;
  tabs?:
    | {
        label: string;
        layout?: ('grid-2' | 'grid-3' | 'grid-4' | 'stacked') | null;
        showTabSubheading?: boolean | null;
        subheading?: string | null;
        content?:
          | (
              | CardLrgBlock
              | CardMedBlock
              | CardWideBlock
              | CardEventBlock
              | CardCourseBlock
              | CardBoatBlock
              | CardPersonBlock
              | CardFleetMapBlock
              | FeeItemBlock
              | FeeGroupBlock
              | RichTextContentBlock
            )[]
          | null;
        id?: string | null;
      }[]
    | null;
  emptyMessage?: string | null;
  footerNote?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'sectionTabs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionContentBlock".
 */
export interface SectionContentBlock {
  label?: string | null;
  heading: string;
  body?: string | null;
  actions?:
    | {
        label: string;
        href: string;
        external?: boolean | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'sectionContent';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MembershipApplicationFormBlock".
 */
export interface MembershipApplicationFormBlock {
  /**
   * Labels and copy for the membership application form (matches MembershipApplicationContent.form).
   */
  form:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'membershipApplicationForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormEmbedBlock".
 */
export interface FormEmbedBlock {
  showHeading?: boolean | null;
  sectionHeading?: {
    kicker?: string | null;
    heading: string;
    body?: string | null;
  };
  form: number | Form;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formEmbed';
}
/**
 * Form templates built with the visual form builder (e.g. the membership application).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NauticalMapBlock".
 */
export interface NauticalMapBlock {
  id?: string | null;
  blockName?: string | null;
  blockType: 'nauticalMap';
}
/**
 * Upcoming club trips and cruise logs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cruise-events".
 */
export interface CruiseEvent {
  id: number;
  title: string;
  dates?: string | null;
  yacht?: string | null;
  model?: string | null;
  skipper?: string | null;
  imageSrc?: (number | null) | Media;
  /**
   * Accessible description. Falls back to the asset's own alt text.
   */
  imageAlt?: string | null;
  /**
   * Sort order (ascending).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Scheduled training calendar entries and course slots.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-events".
 */
export interface TrainingEvent {
  id: number;
  title: string;
  dates?: string | null;
  yacht?: string | null;
  model?: string | null;
  skipper?: string | null;
  /**
   * Sort order (ascending).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Entries received from website forms.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Club members and admin staff login accounts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'boats';
        value: number | Boat;
      } | null)
    | ({
        relationTo: 'cruise-events';
        value: number | CruiseEvent;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'training-events';
        value: number | TrainingEvent;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  pageSections?:
    | T
    | {
        heroHome?: T | HeroHomeBlockSelect<T>;
        sectionHeader?: T | SectionHeaderBlockSelect<T>;
        sectionHeading?: T | SectionHeadingBlockSelect<T>;
        sectionImageParalax?: T | SectionImageParalaxBlockSelect<T>;
        sectionImageSide?: T | SectionImageSideBlockSelect<T>;
        sectionBackgroundImage?: T | SectionBackgroundImageBlockSelect<T>;
        sectionCenter?: T | SectionCenterBlockSelect<T>;
        sectionGallery?: T | SectionGalleryBlockSelect<T>;
        sectionFleetLocation?: T | SectionFleetLocationBlockSelect<T>;
        sectionFleet?: T | SectionFleetBlockSelect<T>;
        sectionPeople?: T | SectionPeopleBlockSelect<T>;
        sectionParagraphs?: T | SectionParagraphsBlockSelect<T>;
        sectionEvents?: T | SectionEventsBlockSelect<T>;
        sectionCards?: T | SectionCardsBlockSelect<T>;
        sectionTabs?: T | SectionTabsBlockSelect<T>;
        sectionContent?: T | SectionContentBlockSelect<T>;
        membershipApplicationForm?: T | MembershipApplicationFormBlockSelect<T>;
        formEmbed?: T | FormEmbedBlockSelect<T>;
        nauticalMap?: T | NauticalMapBlockSelect<T>;
      };
  nav?:
    | T
    | {
        showIn?: T;
        navLabel?: T;
        navOrder?: T;
        divider?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroHomeBlock_select".
 */
export interface HeroHomeBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  coordinates?: T;
  backgroundImage?: T;
  backgroundAlt?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  actions?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionHeaderBlock_select".
 */
export interface SectionHeaderBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  body?: T;
  image?: T;
  imageAlt?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
        external?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionHeadingBlock_select".
 */
export interface SectionHeadingBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  body?: T;
  as?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionImageParalaxBlock_select".
 */
export interface SectionImageParalaxBlockSelect<T extends boolean = true> {
  showHeading?: T;
  sectionHeading?:
    | T
    | {
        kicker?: T;
        heading?: T;
        body?: T;
      };
  kicker?: T;
  heading?: T;
  body?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
        external?: T;
      };
  image?: T;
  imageAlt?: T;
  align?: T;
  variant?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionImageSideBlock_select".
 */
export interface SectionImageSideBlockSelect<T extends boolean = true> {
  showHeading?: T;
  sectionHeading?:
    | T
    | {
        kicker?: T;
        heading?: T;
        body?: T;
      };
  boat?: T;
  imagePosition?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionBackgroundImageBlock_select".
 */
export interface SectionBackgroundImageBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  body?: T;
  ctaLabel?: T;
  ctaHref?: T;
  image?: T;
  imageAlt?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionCenterBlock_select".
 */
export interface SectionCenterBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  ctaLabel?: T;
  ctaHref?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionGalleryBlock_select".
 */
export interface SectionGalleryBlockSelect<T extends boolean = true> {
  showHeading?: T;
  sectionHeading?:
    | T
    | {
        kicker?: T;
        heading?: T;
        body?: T;
      };
  image?: T;
  alt?: T;
  overlayImage?: T;
  overlayAlt?: T;
  totalSlides?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionFleetLocationBlock_select".
 */
export interface SectionFleetLocationBlockSelect<T extends boolean = true> {
  flush?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionFleetBlock_select".
 */
export interface SectionFleetBlockSelect<T extends boolean = true> {
  showHeading?: T;
  sectionHeading?:
    | T
    | {
        kicker?: T;
        heading?: T;
        body?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionPeopleBlock_select".
 */
export interface SectionPeopleBlockSelect<T extends boolean = true> {
  showHeading?: T;
  sectionHeading?:
    | T
    | {
        kicker?: T;
        heading?: T;
        body?: T;
      };
  group?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionParagraphsBlock_select".
 */
export interface SectionParagraphsBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  paragraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
        external?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionEventsBlock_select".
 */
export interface SectionEventsBlockSelect<T extends boolean = true> {
  showHeading?: T;
  sectionHeading?:
    | T
    | {
        kicker?: T;
        heading?: T;
        body?: T;
      };
  source?: T;
  display?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionCardsBlock_select".
 */
export interface SectionCardsBlockSelect<T extends boolean = true> {
  showHeading?: T;
  sectionHeading?:
    | T
    | {
        kicker?: T;
        heading?: T;
        body?: T;
      };
  columns?: T;
  cards?:
    | T
    | {
        cardLrg?: T | CardLrgBlockSelect<T>;
        cardMed?: T | CardMedBlockSelect<T>;
        cardWide?: T | CardWideBlockSelect<T>;
        cardEvent?: T | CardEventBlockSelect<T>;
        cardCourse?: T | CardCourseBlockSelect<T>;
        cardBoat?: T | CardBoatBlockSelect<T>;
        cardPerson?: T | CardPersonBlockSelect<T>;
        cardFleetMap?: T | CardFleetMapBlockSelect<T>;
        feeItem?: T | FeeItemBlockSelect<T>;
        feeGroup?: T | FeeGroupBlockSelect<T>;
        richText?: T | RichTextContentBlockSelect<T>;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardLrgBlock_select".
 */
export interface CardLrgBlockSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  body?:
    | T
    | {
        paragraph?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        list?:
          | T
          | {
              variant?: T;
              items?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        orderedList?:
          | T
          | {
              variant?: T;
              items?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        break?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
        external?: T;
      };
  variant?: T;
  bordered?: T;
  fullWidth?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardMedBlock_select".
 */
export interface CardMedBlockSelect<T extends boolean = true> {
  heading?: T;
  body?:
    | T
    | {
        paragraph?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        list?:
          | T
          | {
              variant?: T;
              items?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        orderedList?:
          | T
          | {
              variant?: T;
              items?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        break?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
      };
  fullWidth?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardWideBlock_select".
 */
export interface CardWideBlockSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardEventBlock_select".
 */
export interface CardEventBlockSelect<T extends boolean = true> {
  title?: T;
  dates?: T;
  yacht?: T;
  model?: T;
  skipper?: T;
  image?: T;
  imageAlt?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardCourseBlock_select".
 */
export interface CardCourseBlockSelect<T extends boolean = true> {
  course?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardBoatBlock_select".
 */
export interface CardBoatBlockSelect<T extends boolean = true> {
  boat?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardPersonBlock_select".
 */
export interface CardPersonBlockSelect<T extends boolean = true> {
  person?: T;
  layout?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardFleetMapBlock_select".
 */
export interface CardFleetMapBlockSelect<T extends boolean = true> {
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeeItemBlock_select".
 */
export interface FeeItemBlockSelect<T extends boolean = true> {
  heading?: T;
  price?: T;
  unit?: T;
  description?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeeGroupBlock_select".
 */
export interface FeeGroupBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  note?: T;
  fees?:
    | T
    | {
        feeItem?: T | FeeItemBlockSelect<T>;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextContentBlock_select".
 */
export interface RichTextContentBlockSelect<T extends boolean = true> {
  body?:
    | T
    | {
        paragraph?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        list?:
          | T
          | {
              variant?: T;
              items?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        orderedList?:
          | T
          | {
              variant?: T;
              items?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        break?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
      };
  size?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionTabsBlock_select".
 */
export interface SectionTabsBlockSelect<T extends boolean = true> {
  ariaLabel?: T;
  tabs?:
    | T
    | {
        label?: T;
        layout?: T;
        showTabSubheading?: T;
        subheading?: T;
        content?:
          | T
          | {
              cardLrg?: T | CardLrgBlockSelect<T>;
              cardMed?: T | CardMedBlockSelect<T>;
              cardWide?: T | CardWideBlockSelect<T>;
              cardEvent?: T | CardEventBlockSelect<T>;
              cardCourse?: T | CardCourseBlockSelect<T>;
              cardBoat?: T | CardBoatBlockSelect<T>;
              cardPerson?: T | CardPersonBlockSelect<T>;
              cardFleetMap?: T | CardFleetMapBlockSelect<T>;
              feeItem?: T | FeeItemBlockSelect<T>;
              feeGroup?: T | FeeGroupBlockSelect<T>;
              richText?: T | RichTextContentBlockSelect<T>;
            };
        id?: T;
      };
  emptyMessage?: T;
  footerNote?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionContentBlock_select".
 */
export interface SectionContentBlockSelect<T extends boolean = true> {
  label?: T;
  heading?: T;
  body?: T;
  actions?:
    | T
    | {
        label?: T;
        href?: T;
        external?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MembershipApplicationFormBlock_select".
 */
export interface MembershipApplicationFormBlockSelect<T extends boolean = true> {
  form?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormEmbedBlock_select".
 */
export interface FormEmbedBlockSelect<T extends boolean = true> {
  showHeading?: T;
  sectionHeading?:
    | T
    | {
        kicker?: T;
        heading?: T;
        body?: T;
      };
  form?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NauticalMapBlock_select".
 */
export interface NauticalMapBlockSelect<T extends boolean = true> {
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "boats_select".
 */
export interface BoatsSelect<T extends boolean = true> {
  name?: T;
  model?: T;
  year?: T;
  description?: T;
  photo?: T;
  photoAlt?: T;
  specsLeft?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  specsRight?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  mmsi?: T;
  lastPosition?:
    | T
    | {
        lat?: T;
        lon?: T;
        sog?: T;
        cog?: T;
        reportedAt?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cruise-events_select".
 */
export interface CruiseEventsSelect<T extends boolean = true> {
  title?: T;
  dates?: T;
  yacht?: T;
  model?: T;
  skipper?: T;
  imageSrc?: T;
  imageAlt?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  tab?: T;
  level?: T;
  desc?: T;
  items?:
    | T
    | {
        item?: T;
        id?: T;
      };
  prices?:
    | T
    | {
        from?: T;
        til?: T;
        amount?: T;
        duration?: T;
        id?: T;
      };
  notes?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-events_select".
 */
export interface TrainingEventsSelect<T extends boolean = true> {
  title?: T;
  dates?: T;
  yacht?: T;
  model?: T;
  skipper?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  dept?: T;
  email?: T;
  photo?: T;
  photoAlt?: T;
  group?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Logo and header buttons. Navigation links are created automatically from pages marked “Show in header” on each page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logoSrc?: string | null;
  logoAlt?: string | null;
  logoHref?: string | null;
  headerJoinLabel?: string | null;
  joinHref?: string | null;
  membersLabel?: string | null;
  membersHref?: string | null;
  primaryNavLabel?: string | null;
  mobileNavLabel?: string | null;
  openNavLabel?: string | null;
  closeNavLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Contact details, artwork and extra links. Page links come from pages marked “Show in footer”.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  contactHeading?: string | null;
  email?: string | null;
  facebookLabel?: string | null;
  facebookUrl?: string | null;
  coordinates?: string | null;
  location?: string | null;
  copyright?: string | null;
  registration?: string | null;
  footerLogoSrc?: string | null;
  footerBackgroundSrc?: string | null;
  footerCompassSrc?: string | null;
  siteFooterBackgroundSrc?: string | null;
  extraLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The fleet's base location / home port map.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fleet-location".
 */
export interface FleetLocation {
  id: number;
  heading?: string | null;
  body?: string | null;
  mapAriaLabel?: string | null;
  mapSrc?: string | null;
  logoSrc?: string | null;
  concordeMarkerSrc?: string | null;
  speedbirdMarkerSrc?: string | null;
  concordeLabel?: string | null;
  speedbirdLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Interactive route tracker map shown on the Cruises page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cruise-map".
 */
export interface CruiseMap {
  id: number;
  mapSrc?: string | null;
  mapAlt?: string | null;
  logoSrc?: string | null;
  speedbirdMarkerSrc?: string | null;
  speedbirdMarkerAlt?: string | null;
  concordeMarkerSrc?: string | null;
  concordeMarkerAlt?: string | null;
  concordeLabel?: string | null;
  speedbirdLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Default SEO metadata for the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  metadata?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logoSrc?: T;
  logoAlt?: T;
  logoHref?: T;
  headerJoinLabel?: T;
  joinHref?: T;
  membersLabel?: T;
  membersHref?: T;
  primaryNavLabel?: T;
  mobileNavLabel?: T;
  openNavLabel?: T;
  closeNavLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  contactHeading?: T;
  email?: T;
  facebookLabel?: T;
  facebookUrl?: T;
  coordinates?: T;
  location?: T;
  copyright?: T;
  registration?: T;
  footerLogoSrc?: T;
  footerBackgroundSrc?: T;
  footerCompassSrc?: T;
  siteFooterBackgroundSrc?: T;
  extraLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fleet-location_select".
 */
export interface FleetLocationSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  mapAriaLabel?: T;
  mapSrc?: T;
  logoSrc?: T;
  concordeMarkerSrc?: T;
  speedbirdMarkerSrc?: T;
  concordeLabel?: T;
  speedbirdLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cruise-map_select".
 */
export interface CruiseMapSelect<T extends boolean = true> {
  mapSrc?: T;
  mapAlt?: T;
  logoSrc?: T;
  speedbirdMarkerSrc?: T;
  speedbirdMarkerAlt?: T;
  concordeMarkerSrc?: T;
  concordeMarkerAlt?: T;
  concordeLabel?: T;
  speedbirdLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  metadata?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}